### PR TITLE
Add configuration to send build scans to https://ge.apache.org

### PR DESCRIPTION
**Pull request by clayburn**

### CODE REVIEW

**Comment by guylabs** [comment]
Hi @ppalaga,

the Apache foundation has a Gradle Enterprise instance running at  https://ge.apache.org. This instance can be used for any Apache project and projects can opt in for free.

This change enables using this instance of Gradle Enterprise for the Maven daemon project. Once merged, you get faster builds instantaneously due to Gradle's performance accelerations techniques for Maven, like build caching (remote build caching will come in summer for Apache projects).

It will as well publish build scans for every execution of a build on CI as well as on any local developer machine to get insights into the build, ease investigation of failures, reason about outcomes and so forth.

You can read more about it [here](https://docs.gradle.com/enterprise/maven-get-started/).

If you have any questions feel free to ping us.

Looking forward to have the Maven daemon project using ge.apache.org.

Regarding the integration test failures with these changes, I'll need to check with @oehme as we might need to reopen https://github.com/apache/maven-mvnd/issues/725. We'll keep you posted.

**Comment by oehme** [comment]
The integ tests have their working dir inside the main project's target folder. So when they search for the `.mvn` directory and they don't have one themselves, they find the dir you just added. The fix would be to make sure that each integ test has at least an empty `.mvn` directory, so it doesn't search upwards. We do the same in the integ tests of our extension.

**Comment by guylabs** [comment]
@ppalaga any update on this? Would you be interested in a short call to answer questions and show you potential benefits of using Gradle Enterprise?

**Comment by ppalaga** [comment]
Sorry gentlemen, no time at all for mvnd this month.

**Comment by guylabs** [comment]
Hi @ppalaga, gentle ping :)

**Comment by clayburn** [comment]
I've rebased this with the latest changes in `master` and with the latest plugin version. Let me know if there are any questions or more information needed.

**Comment by gnodet** [comment]
> I've rebased this with the latest changes in `master` and with the latest plugin version. Let me know if there are any questions or more information needed.

Is there any maven based project at Apache using this extension so far ? It seems there's only `beam` which is using gradle.

**Comment by clayburn** [comment]
> > I've rebased this with the latest changes in `master` and with the latest plugin version. Let me know if there are any questions or more information needed.
> 
> Is there any maven based project at Apache using this extension so far ? It seems there's only `beam` which is using gradle.

You can filter on [just Maven projects](https://ge.apache.org/scans?search.buildToolType=maven&search.timeZoneId=America/Chicago), but [Pulsar](https://ge.apache.org/scans?search.relativeStartTime=P28D&search.rootProjectNames=Pulsar&search.timeZoneId=America/Chicago), [Curator](https://ge.apache.org/scans?search.relativeStartTime=P28D&search.rootProjectNames=*Curator*&search.timeZoneId=America/Chicago), and [SCIMple](https://ge.apache.org/scans?search.relativeStartTime=P28D&search.rootProjectNames=*SCIM*&search.timeZoneId=America/Chicago) are currently using it. Beam just happens to constitute a large percentage of the scans right now.

**Pull request merged**
