### PR TITLE
Align mvnd m39 with Maven 3.9.x re config interpolation

### LINKED ISSUE #910: maven.config ${session.rootDirectory} interpolation is not working
Context: https://github.com/trinodb/trino/pull/20486 https://github.com/trinodb/trino/pull/20734

`${session.rootDirectory}` is not interpolated by `mvnd` when used in the `.mvn/maven.config` to configure modernizer plugin like this:

`-Dmodernizer.violationsFile=${session.rootDirectory}/.mvn/modernizer/violations.xml`

Under mvnd it results in: 

```
[ERROR] Failed to execute goal org.gaul:modernizer-maven-plugin:2.7.0:modernizer (modernizer) on project trino-root: Error opening violation file: ${session.rootDirectory}/.mvn/modernizer/violations.xml: ${session.rootDirectory}/.mvn/modernizer/violations.xm
l (No such file or directory) -> [Help 1]
```

### PR DESCRIPTION
**Pull request by cstamas**
Port Maven 3.9.6 config and new properties (session.root/top) interpolation into Daemon m39.

The IT got this property as it triggers exception (failure) if mvn39 could not "discover" top directory.

Fixes #910

### CODE REVIEW

**Comment by cstamas** [comment]
@wendigo ping

**Review by gnodet — APPROVED** [review]

**Comment by cstamas** [comment]
@wendigo Would be grateful if you build mvnd locally and try it with Trino build, it should now work OOTB. No need for native and all that, just `mvn clean install` and use it on Trino build. Thanks!

**Comment by wendigo** [comment]
Will do @cstamas

**Comment by wendigo** [comment]
@cstamas unfortunately still doesn't work for our case. I've tried reapplying: https://github.com/trinodb/trino/commit/ff1cddbd31d70610952922b19c13bd957e33f00f and that works in mvn but not in mvnd

**Comment by wendigo** [comment]
Adding `-Dmodernizer.violationsFile=${session.rootDirectory}/.mvn/modernizer/violations.xml` to the `.mvn/maven.config` ends with the exception: 
```
[ERROR] Failed to execute goal org.gaul:modernizer-maven-plugin:2.7.0:modernizer (modernizer) on project trino-root: Error opening violation file: ${session.rootDirectory}/.mvn/modernizer/violations.xml: ${session.rootDirectory}/.mvn/modernizer/violations.xml (No such file or directory) -> [Help 1]
```

**Pull request merged**
