### PR TITLE
Ignore smart-builder core extension, if present.

### LINKED ISSUE #912: Detect smart builder in .mvn/extensions.xml and ignore it
As currently it fails:
```
class io.takari.maven.builder.smart.DependencyGraph cannot be cast to class io.takari.maven.builder.smart.DependencyGraph (io.takari.maven.builder.smart.DependencyGraph is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @97e1986; io.takari.maven.builder.smart.DependencyGraph is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @63bde6c2)
```

### PR DESCRIPTION
**Pull request by cstamas**
Fixes #912

### CODE REVIEW

**Comment by wendigo** [comment]
@gnodet can we get this merged and expect new release soon :)?

**Comment by cstamas** [comment]
Do not merge pls, I want to extend this pr: with user configurable GA list to ignore (where smart builder is present "by default").

**Comment by cstamas** [comment]
@ppalaga @gnodet @wendigo pls review

**Comment by cstamas** [comment]
ping

**Review by gnodet — APPROVED** [review]

**Comment by cstamas** [comment]
```
[INFO] ------------------------------------------------------------------------
[ERROR] class io.takari.maven.builder.smart.DependencyGraph cannot be cast to class io.takari.maven.builder.smart.DependencyGraph (io.takari.maven.builder.smart.DependencyGraph is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @17a7cec2; io.takari.maven.builder.smart.DependencyGraph is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @6a9b0a6f)java.lang.ClassCastException: class io.takari.maven.builder.smart.DependencyGraph cannot be cast to class io.takari.maven.builder.smart.DependencyGraph (io.takari.maven.builder.smart.DependencyGraph is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @17a7cec2; io.takari.maven.builder.smart.DependencyGraph is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @6a9b0a6f)
    at io.takari.maven.builder.smart.DependencyGraph.fromMaven (DependencyGraph.java:40)
    at io.takari.maven.builder.smart.SmartBuilder.build (SmartBuilder.java:88)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.DaemonMavenCli.execute (DaemonMavenCli.java:858)
    at org.apache.maven.cli.DaemonMavenCli.doMain (DaemonMavenCli.java:253)
    at org.apache.maven.cli.DaemonMavenCli.main (DaemonMavenCli.java:230)
    at org.mvndaemon.mvnd.daemon.Server.handle (Server.java:612)
    at org.mvndaemon.mvnd.daemon.Server.client (Server.java:288)
    at org.mvndaemon.mvnd.daemon.Server.lambda$accept$2 (Server.java:250)
    at java.lang.Thread.run (Thread.java:1570)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

Also, 
```
mvnd clean install -e -Dmvnd.coreExtensionsExclude=io.takari.maven:takari-smart-builder
```

works but seems kinda default value is ignored?

@gnodet @ppalaga

**Comment by wendigo** [comment]
Just tested the master build with Trino and it seems to ignore the default property value for `MVND_CORE_EXTENSIONS_EXCLUDE` while the explicitly passed `-Dmvnd.coreExtensionsExclude` works as expected.

**Comment by cstamas** [comment]
Def value handling here https://github.com/apache/maven-mvnd/pull/953

**Pull request merged**
