### PR TITLE
Switch to maven 4.0.0-alpha-2

### PR DESCRIPTION
**Pull request by gnodet**

### CODE REVIEW

**Comment by gzm55** [comment]
hi @gnodet , will mvnd be published with an alpha version of maven?

**Comment by gnodet** [comment]
> hi @gnodet , will mvnd be published with an alpha version of maven?

Not sure yet how to handle that.  We may want to create a branch for supporting maven 3.x.  And not sure about the naming yet.

**Comment by gzm55** [comment]
> > hi @gnodet , will mvnd be published with an alpha version of maven?
> 
> Not sure yet how to handle that. We may want to create a branch for supporting maven 3.x. And not sure about the naming yet.

imo, stable release should depend on stable dependency, alpha/beta release can depend anything.

**Comment by gnodet** [comment]
> > hi @gnodet , will mvnd be published with an alpha version of maven?
> 
> Not sure yet how to handle that. We may want to create a branch for supporting maven 3.x. And not sure about the naming yet.

I've create a mvnd-0.9.x branch.  I'll merge this PR in master and I plan to release a 1.0.0-m1 soon.  I'd like to integrate [maven build cache extension](https://maven.apache.org/extensions/maven-build-cache-extension/) in mvnd first.

**Pull request merged**
